# apt-get isntall zsh, chsh /bin/zsh
# wget --no-check-certificate http://install.ohmyz.sh -O - | sh
# cd ~/.oh-my-zsh && git clone git://github.com/zsh-users/zsh-syntax-highlighting.git 

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="dracula"

plugins=(git)

alias date="date '+%F  %r'"
alias gitcommit='git commit -m "$(date)"'

function dock {
    docker exec -it $1 zsh
}

export LANG=ko_KR.UTF-8
export LANGUAGE=en_US:en
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages:/usr/local/python2.7/dist-packages:/usr/bin/python
# export PATH=$PATH:/opt/local/bin:/opt/local/sbin:/usr/local/mysql/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

source $ZSH/oh-my-zsh.sh
source ~/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
